Images to Users
Unitec-Segebre/Unitec-Ingenieria-de-Software-I pull request #29
Opened 2017-03-08 01:41 UTC by jramonrod

Added images to users, forgot to pull request here it is

2017-03-08 20:25 UTC, Segebre requested changes
Lo del new, ya hay un modal para new y por ende no deberia de estar esa view

2017-03-08 20:25 UTC, Segebre commented on app/views/users/new.html.erb
> +<div class="row">
Why would you add a new if it is already a modal

2017-03-08 20:25 UTC, Segebre commented on app/views/users/show.html.erb
> +                                <td><%=link_to(image_tag(@user.get_image,:class=>"img_style"),@user) %></td>
Def size

2017-03-09 04:27 UTC, jramonrod commented on app/views/users/show.html.erb
> +                                <td><%=link_to(image_tag(@user.get_image,:class=>"img_style"),@user) %></td>
Alright I removed it, also added the add images to new user also renamed _form.erb to _form.html.erb

2017-03-09 05:28 UTC, closed without merging